version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-insighttestai}
      POSTGRES_USER: ${DB_USER:-insight}
      POSTGRES_PASSWORD: ${DB_PASS:-insightp}
    ports:
      - "5432:5432"
    volumes:
      - "${PGDATA_PATH:-./data}:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5