version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-insight}
      POSTGRES_USER: ${POSTGRES_USER:-insight}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insight}
    ports:
      - "5432:5432"
    volumes:
      - "${PGDATA_PATH:-/d/Mount/InsightTestAI}:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

