version: '3.9'

services:
  # PostgreSQL Database với pgvector extension cho development
  postgres:
    image: pgvector/pgvector:pg16
    container_name: insighttestai-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-insighttestai}
      POSTGRES_USER: ${POSTGRES_USER:-insight}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-insightp}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${PGDATA_PATH:-./db/data_dev}:/var/lib/postgresql/data
      - ./server/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - insighttestai-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data_dev:

networks:
  insighttestai-network-dev:
    driver: bridge
